[package]
name = "cmake-analyzer"
version = "0.1.0"
edition = "2024"
[[bin]]
name = "playground"
path = "./tests/playground.rs"

[[bin]]
name = "lexer"
path = "./cli/parser/lexer/main.rs"

[[bin]]
name = "nparser"
path = "./cli/parser/nparser/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
owo-colors = "4.4.0"
tokio = { version = "1.53.1", features = ["full", "io-uring"] }
